name: '[ CI ] | Continuous Integration'

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      spec:
        description: The SEMVER specification.
        required: true
        type: choice
        default: patch
        options:
          - 'major'
          - 'minor'
          - 'patch'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: ./
        with:
          github-token: ${{ github.token }}
